// edge_personalization.ino
// ─────────────────────────────────────────────────────────────────────────────
// ESP32 on-device incremental learning for stress detection.
//
// Changes vs. original:
//  1. Loads REAL generic model via #include "model_weights.h" (auto-generated
//     by export_generic_model.py) — no more zero stubs.
//  2. sgd_update() now applies EWC (Elastic Weight Consolidation) penalty to
//     match the Python simulation in part2_edge_simulation_aggressive_tuning.py.
//  3. Scaling is kept in Python / send_data_to_esp.py (Option A) — the ESP32
//     receives pre-scaled floats, so scale_features() is not called at runtime.
//     scaler_mean / scaler_std are loaded for completeness if ever switching
//     to fully standalone mode.
// ─────────────────────────────────────────────────────────────────────────────

#include <Arduino.h>
#include <math.h>
#include "model_weights.h"   // ← real weights, generated by export_generic_model.py
                              //   (copy model_weights.h from output/ into sketch folder)

// NUM_FEATURES is defined in model_weights.h (currently 15)
#define BUFFER_SIZE 10

// ──────────────────────────────────────────────────────────────────────────────
// Replay buffer
// ──────────────────────────────────────────────────────────────────────────────
struct ReplayItem {
    float features[NUM_FEATURES];
    uint8_t label;
};

// ──────────────────────────────────────────────────────────────────────────────
// Global mutable model state
// ──────────────────────────────────────────────────────────────────────────────
float current_weights[NUM_FEATURES];
float current_bias;
float scaler_mean[NUM_FEATURES];   // loaded for optional standalone scaling
float scaler_std[NUM_FEATURES];    // loaded for optional standalone scaling

ReplayItem replay_buffer[BUFFER_SIZE];
int buffer_idx   = 0;
int buffer_count = 0;
int update_count = 0;

float lr         = 0.1f;          // matches Python sim lr
float ewc_lambda = 0.001f;        // matches Python sim ewc_lambda

// ──────────────────────────────────────────────────────────────────────────────
// Metrics
// ──────────────────────────────────────────────────────────────────────────────
int true_positives   = 0;
int false_positives  = 0;
int true_negatives   = 0;
int false_negatives  = 0;
int total_predictions   = 0;
int correct_predictions = 0;

// ──────────────────────────────────────────────────────────────────────────────
// Inference scratch
// ──────────────────────────────────────────────────────────────────────────────
float   temp_features[NUM_FEATURES];
bool    features_ready = false;
int     last_prediction = 0;

// ──────────────────────────────────────────────────────────────────────────────
// Model load / save
// ──────────────────────────────────────────────────────────────────────────────

void loadModelFromFlash(float* weights, float* bias,
                        float* mean, float* std_arr) {
    // Copy from const arrays in model_weights.h into mutable RAM
    *bias = GENERIC_BIAS;
    for (int i = 0; i < NUM_FEATURES; i++) {
        weights[i]   = GENERIC_WEIGHTS[i];
        mean[i]      = SCALER_MEAN[i];
        std_arr[i]   = SCALER_STD[i];
    }
    Serial.println("SYS: Generic model loaded from flash (model_weights.h).");
}

void saveModelToSmartCard(float* weights, float bias) {
    // In production: write to NVS, SD card, or smart card peripheral.
    // For now: print personalised weights via Serial for inspection / logging.
    Serial.println("SYS: Saving personalised model ...");
    Serial.print("SYS: bias="); Serial.println(bias, 6);
    Serial.print("SYS: weights=");
    for (int i = 0; i < NUM_FEATURES; i++) {
        Serial.print(weights[i], 6);
        if (i < NUM_FEATURES - 1) Serial.print(",");
    }
    Serial.println();
}

// ──────────────────────────────────────────────────────────────────────────────
// Core maths
// ──────────────────────────────────────────────────────────────────────────────

float sigmoid(float x) {
    if (x >  50.0f) return 1.0f;
    if (x < -50.0f) return 0.0f;
    return 1.0f / (1.0f + expf(-x));
}

float predict_prob(float* features) {
    float z = current_bias;
    for (int i = 0; i < NUM_FEATURES; i++) {
        z += current_weights[i] * features[i];
    }
    return sigmoid(z);
}

// Optional: use if switching to fully standalone mode (raw features from sensor)
void scale_features(float* raw, float* scaled) {
    for (int i = 0; i < NUM_FEATURES; i++) {
        scaled[i] = (raw[i] - scaler_mean[i]) / scaler_std[i];
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// SGD update WITH EWC penalty
// Matches Python sim:  grad_w = clipped_error * features - ewc_lambda * F * (w - w0)
// ──────────────────────────────────────────────────────────────────────────────
void sgd_update(float* features, uint8_t label) {
    float pred  = predict_prob(features);
    float error = (float)label - pred;
    float clipped = fmaxf(-1.0f, fminf(1.0f, error));

    // Bias update with EWC
    float ewc_pen_bias = ewc_lambda * F_BIAS * (current_bias - GENERIC_BIAS);
    float grad_b = clipped - ewc_pen_bias;
    grad_b = fmaxf(-1.0f, fminf(1.0f, grad_b));
    current_bias += lr * grad_b;

    // Weight update with EWC
    for (int i = 0; i < NUM_FEATURES; i++) {
        float ewc_pen = ewc_lambda * F_WEIGHTS[i] * (current_weights[i] - GENERIC_WEIGHTS[i]);
        float grad_w  = clipped * features[i] - ewc_pen;
        grad_w = fmaxf(-1.0f, fminf(1.0f, grad_w));
        current_weights[i] += lr * grad_w;
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Replay buffer helpers
// ──────────────────────────────────────────────────────────────────────────────
void process_replay_buffer() {
    for (int i = 0; i < buffer_count; i++) {
        sgd_update(replay_buffer[i].features, replay_buffer[i].label);
    }
}

void add_to_buffer(float* features, uint8_t label) {
    for (int i = 0; i < NUM_FEATURES; i++) {
        replay_buffer[buffer_idx].features[i] = features[i];
    }
    replay_buffer[buffer_idx].label = label;
    buffer_idx = (buffer_idx + 1) % BUFFER_SIZE;
    if (buffer_count < BUFFER_SIZE) buffer_count++;
}

// ──────────────────────────────────────────────────────────────────────────────
// Serial protocol helpers
// ──────────────────────────────────────────────────────────────────────────────
void parse_features(String line) {
    int feature_index = 0;
    int start_pos = 0;
    int comma_pos = line.indexOf(',');

    while (comma_pos != -1 && feature_index < NUM_FEATURES - 1) {
        temp_features[feature_index++] =
            line.substring(start_pos, comma_pos).toFloat();
        start_pos = comma_pos + 1;
        comma_pos = line.indexOf(',', start_pos);
    }
    if (feature_index < NUM_FEATURES) {
        temp_features[feature_index] = line.substring(start_pos).toFloat();
    }

    // Features arrive pre-scaled from send_data_to_esp.py (Option A).
    // If switching to Option B (raw sensor → scale on device), call:
    //   scale_features(temp_features, temp_features);
    // here before predict_prob().

    features_ready = true;
    float prob = predict_prob(temp_features);
    last_prediction = (prob >= 0.5f) ? 1 : 0;

    Serial.print("Pred:");
    Serial.println(last_prediction);
}

void parse_label(String line) {
    if (!features_ready) {
        Serial.println("ERR: Label received before features.");
        return;
    }

    int colon_pos = line.indexOf(':');
    if (colon_pos == -1) return;

    uint8_t true_label = (uint8_t)line.substring(colon_pos + 1).toInt();

    // Metrics
    total_predictions++;
    if (last_prediction == true_label) {
        correct_predictions++;
        if (true_label == 1) true_positives++;
        else                 true_negatives++;
    } else {
        if (true_label == 1) false_negatives++;
        else                 false_positives++;
    }

    // --- Personalisation: SGD (×10) with EWC, matching Python sim ---
    for (int rep = 0; rep < 10; rep++) {
        sgd_update(temp_features, true_label);
    }
    // ----------------------------------------------------------------

    add_to_buffer(temp_features, true_label);
    update_count++;

    // Replay every 2 samples
    if (update_count % 2 == 0) {
        process_replay_buffer();
    }

    features_ready = false;
    Serial.println("ACK");
}

void handle_end_shift() {
    saveModelToSmartCard(current_weights, current_bias);

    float accuracy = (total_predictions > 0)
        ? ((float)correct_predictions / total_predictions)
        : 0.0f;

    Serial.println("--- END OF SHIFT METRICS ---");
    Serial.print("Accuracy: "); Serial.println(accuracy, 4);
    Serial.println("Confusion Matrix:");
    Serial.print("[["); Serial.print(true_negatives);
    Serial.print("  ");  Serial.print(false_positives); Serial.println("]");
    Serial.print(" [");  Serial.print(false_negatives);
    Serial.print("  ");  Serial.print(true_positives);  Serial.println("]]");

    // Reset state
    total_predictions   = 0; correct_predictions = 0;
    true_positives      = 0; false_positives     = 0;
    true_negatives      = 0; false_negatives     = 0;
    update_count        = 0; buffer_count        = 0; buffer_idx = 0;
}

// ──────────────────────────────────────────────────────────────────────────────
// Arduino entry points
// ──────────────────────────────────────────────────────────────────────────────

void setup() {
    Serial.begin(115200);
    while (!Serial) { ; }
    loadModelFromFlash(current_weights, &current_bias, scaler_mean, scaler_std);
    Serial.println("SYS: ESP32 Edge Personalisation Initialised.");
}

void loop() {
    if (Serial.available() > 0) {
        String line = Serial.readStringUntil('\n');
        line.trim();
        if (line.length() == 0) return;

        if      (line == "END_SHIFT")        handle_end_shift();
        else if (line.startsWith("label:"))  parse_label(line);
        else                                 parse_features(line);
    }
}
