"""
export_scaler_params.py
=======================
For each LOSO simulation (one test subject held out), refit the
StandardScaler on the remaining subjects' data — exactly as the
simulation scripts do — and print / save the mean_ and scale_ arrays
ready to paste into the ESP32 firmware.

The pipeline mirrors part2_edge_simulation_no_replay.py:
  1. Drop NaN rows.
  2. Fit StandardScaler on X_train (all subjects except test subject).
  3. The resulting scaler.mean_ and scaler.scale_ are what the ESP32
     must apply to raw features before running inference.

Output
------
  - Console: C-array initialiser for every subject.
  - File:    output/scaler_params_per_subject.json  (machine-readable)
  - File:    output/scaler_params_per_subject.h     (copy-paste into firmware)
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

# ── Configuration ────────────────────────────────────────────────────────────
SCRIPT_DIR  = Path(__file__).resolve().parent
DATA_PATH   = SCRIPT_DIR / "output" / "wesad_eda_features_phase3.parquet"
OUT_JSON    = SCRIPT_DIR / "output" / "scaler_params_per_subject.json"
OUT_HEADER  = SCRIPT_DIR / "output" / "scaler_params_per_subject.h"

METADATA_COLS = ["subject", "window_id", "binary_label"]
# ─────────────────────────────────────────────────────────────────────────────


def fmt_array(name: str, values, indent: int = 4) -> str:
    """Format a float array as a C initialiser list."""
    sp = " " * indent
    vals = ", ".join(f"{v:.10f}f" for v in values)
    return f"{sp}float {name}[{len(values)}] = {{{vals}}};"


def main():
    print(f"Loading data from {DATA_PATH} …")
    df = pd.read_parquet(DATA_PATH).dropna()

    feature_cols = [c for c in df.columns if c not in METADATA_COLS]
    subjects     = sorted(df["subject"].unique())
    n_features   = len(feature_cols)

    print(f"  {len(df)} windows · {n_features} features · {len(subjects)} subjects\n")
    print(f"Feature order ({n_features}):")
    for i, col in enumerate(feature_cols):
        print(f"  [{i:2d}] {col}")

    all_results = {}
    header_lines = [
        "// scaler_params_per_subject.h",
        "// Auto-generated by export_scaler_params.py",
        "// Each block contains the scaler mean and scale (std) fitted on all",
        "// subjects EXCEPT the test subject (LOSO). Apply z = (x - mean) / scale",
        "// to each raw feature before passing to the logistic regression model.",
        "",
        f"// Feature order: {', '.join(feature_cols)}",
        "",
    ]

    for subj in subjects:
        train_df = df[df["subject"] != subj]
        X_train  = train_df[feature_cols].values

        scaler = StandardScaler()
        scaler.fit(X_train)

        mean_arr  = scaler.mean_.tolist()
        scale_arr = scaler.scale_.tolist()

        all_results[subj] = {
            "feature_names": feature_cols,
            "mean":  mean_arr,
            "scale": scale_arr,
        }

        # ── Console output ───────────────────────────────────────────────────
        print("=" * 70)
        print(f"  Subject: {subj}  (trained on {len(train_df)} windows)")
        print("=" * 70)

        print("\n  // Scaler MEAN  — subtract from raw feature value")
        print("  float scaler_mean[{}] = {{".format(n_features))
        for i, (col, v) in enumerate(zip(feature_cols, mean_arr)):
            comma = "," if i < n_features - 1 else ""
            print(f"    {v:.10f}f{comma}  // [{i}] {col}")
        print("  };")

        print("\n  // Scaler SCALE (std dev) — divide after subtracting mean")
        print("  float scaler_scale[{}] = {{".format(n_features))
        for i, (col, v) in enumerate(zip(feature_cols, scale_arr)):
            comma = "," if i < n_features - 1 else ""
            print(f"    {v:.10f}f{comma}  // [{i}] {col}")
        print("  };")
        print()

        # ── Header block ─────────────────────────────────────────────────────
        safe = subj.replace(" ", "_")
        header_lines += [
            f"// ── Subject {subj} ──────────────────────────────────────────",
            f"#ifdef SUBJECT_{safe}",
            f"  // trained on {len(train_df)} windows from all other subjects",
            fmt_array("scaler_mean",  mean_arr),
            fmt_array("scaler_scale", scale_arr),
            "#endif",
            "",
        ]

    # ── Save JSON ────────────────────────────────────────────────────────────
    with open(OUT_JSON, "w") as f:
        json.dump(all_results, f, indent=2)
    print(f"\n[Saved] {OUT_JSON}")

    # ── Save header ──────────────────────────────────────────────────────────
    with open(OUT_HEADER, "w") as f:
        f.write("\n".join(header_lines))
    print(f"[Saved] {OUT_HEADER}")
    print("\nDone. Paste the relevant block into your ESP32 firmware.")


if __name__ == "__main__":
    main()
