"""
export_generic_model.py
-----------------------
Trains the generic logistic regression model (leave-one-out on the default
test subject) and exports:
  - output/generic_model.json   → human-readable model snapshot
  - output/model_weights.h      → C header ready to #include in the .ino
  - output/generic_model_fisher.json → Fisher diagonal for EWC (also embedded in header)

Usage:
    python export_generic_model.py [--subject S9]
"""

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.exceptions import ConvergenceWarning
import warnings

warnings.filterwarnings("ignore", category=ConvergenceWarning)

# ──────────────────────────────────────────────────────────────────────────────
def float_array_to_c(name: str, values: list[float], per_row: int = 5) -> str:
    """Format a Python float list as a C float array literal."""
    lines = []
    for i in range(0, len(values), per_row):
        chunk = values[i : i + per_row]
        lines.append("    " + ", ".join(f"{v:.8f}f" for v in chunk))
    body = ",\n".join(lines)
    n = len(values)
    return f"const float {name}[{n}] = {{\n{body}\n}};"


def generate_c_header(export: dict, subject: str) -> str:
    n = len(export["weights"])
    lines = [
        "// model_weights.h — AUTO-GENERATED by export_generic_model.py",
        f"// Generic model trained on all subjects EXCEPT {subject}",
        "// DO NOT EDIT MANUALLY — re-run export_generic_model.py to refresh",
        "",
        "#pragma once",
        "",
        f"#define NUM_FEATURES {n}",
        "",
        float_array_to_c("GENERIC_WEIGHTS", export["weights"]),
        "",
        f"const float GENERIC_BIAS = {export['bias']:.8f}f;",
        "",
        float_array_to_c("SCALER_MEAN", export["scaler_mean"]),
        "",
        float_array_to_c("SCALER_STD", export["scaler_std"]),
        "",
        float_array_to_c("F_WEIGHTS", export["fisher_weights"]),
        "",
        f"const float F_BIAS = {export['fisher_bias']:.8f}f;",
        "",
    ]
    return "\n".join(lines)


# ──────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--subject",
        type=str,
        default="S9",
        help="Test subject to hold out (all others used for training)",
    )
    parser.add_argument(
        "--output-dir", type=str, default="output", help="Output directory"
    )
    args = parser.parse_args()

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # ── Load data ──────────────────────────────────────────────────────────────
    print(f"Loading features from {out_dir}/wesad_eda_features_phase3.parquet …")
    df = pd.read_parquet(out_dir / "wesad_eda_features_phase3.parquet")
    df = df.dropna()

    metadata_cols = ["subject", "window_id", "binary_label"]
    feature_cols = [c for c in df.columns if c not in metadata_cols]
    print(f"Features ({len(feature_cols)}): {feature_cols}")

    train_df = df[df["subject"] != args.subject]
    print(
        f"Training on {len(train_df)} windows "
        f"(all subjects except {args.subject})."
    )

    X_train = train_df[feature_cols].values
    y_train = train_df["binary_label"].values

    # ── Scale ──────────────────────────────────────────────────────────────────
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)

    # ── Train generic model ────────────────────────────────────────────────────
    clf = LogisticRegression(random_state=42, max_iter=1000)
    clf.fit(X_train_scaled, y_train)

    weights = clf.coef_[0]
    bias = float(clf.intercept_[0])
    print(f"\nGeneric model trained.  bias = {bias:.6f}")

    # ── Fisher diagonal (EWC) ──────────────────────────────────────────────────
    p_train = clf.predict_proba(X_train_scaled)[:, 1]
    grad_w = (y_train - p_train)[:, np.newaxis] * X_train_scaled   # (N, 15)
    F_weights = np.mean(grad_w ** 2, axis=0)                        # (15,)
    F_bias = float(np.mean((y_train - p_train) ** 2))
    print(f"EWC Fisher diagonal computed.  F_bias = {F_bias:.6f}")

    # ── Build export dict ──────────────────────────────────────────────────────
    export = {
        "held_out_subject": args.subject,
        "feature_names": feature_cols,
        "num_features": len(feature_cols),
        "weights": weights.tolist(),
        "bias": bias,
        "scaler_mean": scaler.mean_.tolist(),
        "scaler_std": scaler.scale_.tolist(),
        "fisher_weights": F_weights.tolist(),
        "fisher_bias": F_bias,
    }

    # ── Save JSON ──────────────────────────────────────────────────────────────
    json_path = out_dir / "generic_model.json"
    with open(json_path, "w") as f:
        json.dump(export, f, indent=2)
    print(f"\nSaved JSON  → {json_path}")

    # ── Save C header ──────────────────────────────────────────────────────────
    header_path = out_dir / "model_weights.h"
    with open(header_path, "w") as f:
        f.write(generate_c_header(export, args.subject))
    print(f"Saved header → {header_path}")

    # ── Print size estimate ────────────────────────────────────────────────────
    n = len(feature_cols)
    num_arrays = 4  # weights, scaler_mean, scaler_std, fisher_weights
    num_scalars = 3  # bias, F_bias, GENERIC_BIAS
    flash_bytes = (n * num_arrays + num_scalars) * 4
    replay_item_bytes = n * 4 + 1            # features + 1-byte label
    sram_mutable = (n * 3 + 3) * 4          # current_weights, scaler copies, temps
    sram_replay = replay_item_bytes * 10     # BUFFER_SIZE=10
    sram_total = sram_mutable + sram_replay + 50  # +50 misc counters

    print("\n─── Estimated Resource Usage ───────────────────────────────")
    print(f"  Flash (model constants in .rodata) : {flash_bytes:>5} bytes")
    print(f"  SRAM  (mutable runtime arrays)     : {sram_mutable:>5} bytes")
    print(f"  SRAM  (replay buffer × 10)         : {sram_replay:>5} bytes")
    print(f"  SRAM  (total estimate)             : {sram_total:>5} bytes")
    print("────────────────────────────────────────────────────────────")


if __name__ == "__main__":
    main()
